name: Build client App and Commit
on:
  push:
    branches:
      - master
jobs:
  build-client:
    name: Build client application.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Configure git
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}
      - name: Remove previous client application build.
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./server/public
      - name: Install Dependencies for client application.
        working-directory: ./client
        run: npm install
      - name: Build client application.
        working-directory: ./client
        run: npm run build
      - name: Commit
        run: |
          git add -A .
          git commit -m "Client application builded by CI workflow"
          git push origin master
