name: Build client App and Commit
on:
  push:
    branches:
      - master
jobs:
  build-client:
    name: Build client application.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Remove previous client application build.
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./server/public
      - name: Install Dependencies for client application.
        working-directory: ./client
        run: npm install
      - name: Build client application.
        working-directory: ./client
        run: npm run build
      - name: Commit
        run: |
          git add .
          git commit -m "Client application builded by CI workflow"
          git push
